openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /pets:
    get:
      summary: List all pets
      operationId: listPets
      tags:
        - pets
      responses:
        "200":
          description: A paged array of pets
          content:
            application/json:
              schema:
                type: object
                properties:
                  thing:
                    $ref: "#/components/schemas/LoginStatus"
components:
  schemas:
    LoginStatus:
      enum:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
      x-enumNames:
        - Unknown
        - Success
        - TwoFactorRequiredYubikey
        - TwoFactorRequiredGoogleAuthenticator
        - InvalidEmailOrPassword
        - InvalidToken
        - InvalidRefreshToken
        - InvalidTwoFactorCode
      type: integer
      format: int32
